# Generated by Django 5.0.3 on 2024-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
